### ISSUE TITLE
What is the value range of BlendShapes for 3D models?

### ISSUE THREAD

**Issue by blguweb** [nmfisher/blender_livelinkface#3]
I checked `blender_livelinkface/pylivelinkface.py
```
        value: float
            Value to set the BlendShape to, should be in the range of 0 - 1 for 
            the blendshapes and between -1 and 1 for the head rotation 
            (yaw, pitch, roll).
```
I set the blendshape to 0-1 but there was no change. I want to know what the minimum and maximum values are?

**Comment by nmfisher** [comment]
The min/max values coming from the LiveLinkFace app (or any iPhone app using ARKit blendshapes) are as specified, the range (-1,1) for head rotation and (0,1) for everything else.

What do you mean you "set the blendshape to 0-1 but there was no change"?

**Comment by blguweb** [comment]
Thank you for your reply. I’m sorry I didn’t describe the scene well before. In fact, I imported the model into unity and found that the 0-1 weight did not deform much. The reason is that the weight range in unity is 0-100.
